### ISSUE TITLE
Contribute to Flutter Projects for Hacktoberfest2022!!!

### ISSUE THREAD

**Issue by HemantPra389** [HemantPra389/Flutter-Open-Source-Apps#13]
The biggest opensource festival is live!! Contribute in your favourite cross platform language and get the chance to win Free T-Shirts or a Tree Planted by your name by DigitalOcean..
Happy Hacktoberfest2022!!!!

**Comment by SmartAree** [comment]
Can you assign me any Flutter project, please? I am very disappointed because I wrote an issue about the BMI calculator, you said another contributor did that :(

**Comment by HemantPra389** [comment]
Due to similar application we can't proceed with your application. We are following all the terms of condition of hacktoberfest and can't introduce similar application in our repository. We thankyou for your effort and concern. Happy Hacktoberfest2022!!!!
